language: python
python: 
  - "3.6"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda env create -f=./environment.yml
  - source activate default
  # Useful for debugging any issues with conda
  - conda info -a
script:
  - pylint *
  - nosetests
  - source deactivate
after_success:
  - echo "Successful!"
  - echo "Creating package..."
before_deploy:
  - if [[ "x$TRAVIS_TAG" != "x" ]]; then
      python ./scripts/package.py $TRAVIS_TAG
    fi
deploy:
  skip_cleanup: true
  provider: releases
  api_key: 
    secure: px/9tAPHY13Bn9oa2o+Wc5FJF/0F8iVWZFtYseggKoAFF+naMkOpn1V/V07+7VYHUkbhv6JocEpZCXgp7yv52AVKcoHsJC66PCb4ziCCSo4HAAKyGTxLKKRGQAxVToFbV3Qn7yNjt7YQLb67c3qI6FnjEIqOVeWyzyaNRCpQMPkeFIHpTfBP2C+wA442A7DZ/bcDAWPblMEUPHmmkojJfCgE5wxQfCVY+fIJqcs6Gin1SCfSSrkdTKcjRmSRhVvu5SuqFjX+sR3komc2L9b2bUiC2uHnstwd8tds+ilxCVPEl3IFhWYlfVjHOx5IYIKK9S8uVbJG7Rgqebo+C8lDEwzFFnIXJZkpJq5vH4TU51peqKk5fDX6e4XiQ8qQm+HcOcrcoz0KyUuX9Lp3XmFgrsAgS3wqzW5wjN2SZTPJ0jQrXrem/mS+zlRDOHwc8YeDxTStBZRsUyaoLjbKi6nqnW7uXYWDGq9tej/FX2TRaRG80iGrmj7vnnJJnROMyuR4YRRkYfxamco1gGZju8R5jvFknfiyWRaDtrENJX1SLNPzw5WtTY0yx/UIQma3l8t77cKUzjnnUCfhRchDYutZ5CkTle9q6Rs4LvtbV53bIYSDHoYTU0pTRk/c0/GNqABMlzg4UcgP4KPCbOqmD7Pze3ImefX5u3fGJDYwSHGWW2k=
  file_glob: true
  file: build/*
  on:
    repo: scuba10steve/App-Manager
    tags: true