name: app-manager
channels:
- !!python/unicode
  'conda-forge'
dependencies:
- python=3.6
- pip=9.0.3
- flask=0.12.2
- pylint
- Flask-RESTful=0.3.6
- sqlite
- requests=2.18
- pytest=3.2
- autopep8
- rope
- coverage
- nose=1.3.7
- pyinstaller
- libarchive=3.3.3